# Generated by Django 3.2.3 on 2021-05-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='confirm_password',
            field=models.CharField(default='GHJ', max_length=50),
            preserve_default=False,
        ),
    ]
