# Generated by Django 3.2.3 on 2021-05-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='username',
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(to='blog1.Article'),
        ),
    ]
