# Generated by Django 3.2.3 on 2021-05-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0006_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='username',
        ),
    ]
