# Generated by Django 3.2.3 on 2021-05-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_article_slugtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog1.author'),
        ),
    ]
