# Generated by Django 3.2.3 on 2021-05-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0010_alter_article_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='username',
        ),
    ]
